/*
 * DaCASparqlProcessor
 * This is DaCA's Sparql Processor service.  You can find out more about     us at [https://github.com/catalin-vlas/DaCA](DaCA).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aurelian.hreapca@info.uaic.ro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wade.daca.sparql.client.api;

import com.wade.daca.sparql.client.model.RdfTriple;
import com.wade.daca.sparql.client.ApiCallback;
import com.wade.daca.sparql.client.ApiClient;
import com.wade.daca.sparql.client.ApiException;
import com.wade.daca.sparql.client.ApiResponse;
import com.wade.daca.sparql.client.Configuration;
import com.wade.daca.sparql.client.Pair;
import com.wade.daca.sparql.client.ProgressRequestBody;
import com.wade.daca.sparql.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SparqlApi {
    private ApiClient apiClient;

    public SparqlApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SparqlApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for executeSparqlQuery
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call executeSparqlQueryCall(String namespaceId, String query, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/sparql/query";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (namespaceId != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "namespaceId", namespaceId));
        if (query != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "query", query));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call executeSparqlQueryValidateBeforeCall(String namespaceId, String query, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'namespaceId' is set
        if (namespaceId == null) {
            throw new ApiException("Missing the required parameter 'namespaceId' when calling executeSparqlQuery(Async)");
        }
        
        // verify the required parameter 'query' is set
        if (query == null) {
            throw new ApiException("Missing the required parameter 'query' when calling executeSparqlQuery(Async)");
        }
        
        
        com.squareup.okhttp.Call call = executeSparqlQueryCall(namespaceId, query, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Execute custom SPARQL query
     * 
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @return List&lt;RdfTriple&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<RdfTriple> executeSparqlQuery(String namespaceId, String query) throws ApiException {
        ApiResponse<List<RdfTriple>> resp = executeSparqlQueryWithHttpInfo(namespaceId, query);
        return resp.getData();
    }

    /**
     * Execute custom SPARQL query
     * 
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @return ApiResponse&lt;List&lt;RdfTriple&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<RdfTriple>> executeSparqlQueryWithHttpInfo(String namespaceId, String query) throws ApiException {
        com.squareup.okhttp.Call call = executeSparqlQueryValidateBeforeCall(namespaceId, query, null, null);
        Type localVarReturnType = new TypeToken<List<RdfTriple>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Execute custom SPARQL query (asynchronously)
     * 
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call executeSparqlQueryAsync(String namespaceId, String query, final ApiCallback<List<RdfTriple>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = executeSparqlQueryValidateBeforeCall(namespaceId, query, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<RdfTriple>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for executeSparqlUpdate
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call executeSparqlUpdateCall(String namespaceId, String query, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/sparql/query";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (namespaceId != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "namespaceId", namespaceId));
        if (query != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "query", query));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call executeSparqlUpdateValidateBeforeCall(String namespaceId, String query, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'namespaceId' is set
        if (namespaceId == null) {
            throw new ApiException("Missing the required parameter 'namespaceId' when calling executeSparqlUpdate(Async)");
        }
        
        // verify the required parameter 'query' is set
        if (query == null) {
            throw new ApiException("Missing the required parameter 'query' when calling executeSparqlUpdate(Async)");
        }
        
        
        com.squareup.okhttp.Call call = executeSparqlUpdateCall(namespaceId, query, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Execute custom update SPARQL query
     * 
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void executeSparqlUpdate(String namespaceId, String query) throws ApiException {
        executeSparqlUpdateWithHttpInfo(namespaceId, query);
    }

    /**
     * Execute custom update SPARQL query
     * 
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> executeSparqlUpdateWithHttpInfo(String namespaceId, String query) throws ApiException {
        com.squareup.okhttp.Call call = executeSparqlUpdateValidateBeforeCall(namespaceId, query, null, null);
        return apiClient.execute(call);
    }

    /**
     * Execute custom update SPARQL query (asynchronously)
     * 
     * @param namespaceId The namespace in which the query is run (required)
     * @param query The SPARQL query to be executed (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call executeSparqlUpdateAsync(String namespaceId, String query, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = executeSparqlUpdateValidateBeforeCall(namespaceId, query, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
