/*
 * SparqlProcessor
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wade.daca.sparql.client.api;

import com.wade.daca.sparql.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for NamespaceApi
 */
@Ignore
public class NamespaceApiTest {

    private final NamespaceApi api = new NamespaceApi();

    
    /**
     * Create a new namespace
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNamespaceTest() throws ApiException {
        String namespaceId = null;
        api.createNamespace(namespaceId);

        // TODO: test validations
    }
    
    /**
     * Delete a namespace
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteNamespaceTest() throws ApiException {
        String namespaceId = null;
        api.deleteNamespace(namespaceId);

        // TODO: test validations
    }
    
    /**
     * Get namespaces
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNamespacesTest() throws ApiException {
        List<String> response = api.getNamespaces();

        // TODO: test validations
    }
    
}
