/*
 * SparqlProcessor
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wade.daca.sparql.client.api;

import com.wade.daca.sparql.client.ApiException;
import com.wade.daca.sparql.client.model.RdfTriple;

import java.io.File;

import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for TriplesApi
 */
@Ignore
public class TriplesApiTest {

    private final TriplesApi api = new TriplesApi();

    
    /**
     * Add triples in given namespace
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTriplesTest() throws ApiException {
        String namespaceId = null;
        List<RdfTriple> triples = null;
        api.addTriples(namespaceId, triples);

        // TODO: test validations
    }
    
    /**
     * Add triples from file in given namespace
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTriplesFromFileTest() throws ApiException {
        String namespaceId = null;
        File file = null;
        api.addTriplesFromFile(namespaceId, file);

        // TODO: test validations
    }
    
    /**
     * Get triples of given namespace
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTriplesTest() throws ApiException {
        String namespaceId = null;
        List<RdfTriple> response = api.getTriples(namespaceId);

        // TODO: test validations
    }
    
}
