/*
 * DaCASparqlProcessor
 * This is DaCA's Sparql Processor service.  You can find out more about     us at [https://github.com/catalin-vlas/DaCA](DaCA).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aurelian.hreapca@info.uaic.ro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wade.daca.sparql.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * RdfStats
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-31T15:22:36.080Z")
public class RdfStats {
  @SerializedName("Size")
  private Integer size = null;

  @SerializedName("NrTriples")
  private Integer nrTriples = null;

  @SerializedName("NrNodes")
  private Integer nrNodes = null;

  @SerializedName("NrBlankNodes")
  private Integer nrBlankNodes = null;

  @SerializedName("NrLiterals")
  private Integer nrLiterals = null;

  @SerializedName("NrURINodes")
  private Integer nrURINodes = null;

  @SerializedName("NrType")
  private Integer nrType = null;

  @SerializedName("MaxInDegree")
  private Integer maxInDegree = null;

  @SerializedName("MaxOutDegree")
  private Integer maxOutDegree = null;

  @SerializedName("MaxDegree")
  private Integer maxDegree = null;

  @SerializedName("MaxInDegreeNode")
  private String maxInDegreeNode = null;

  @SerializedName("MaxOutDegreeNode")
  private String maxOutDegreeNode = null;

  @SerializedName("MaxDegreeNode")
  private String maxDegreeNode = null;

  @SerializedName("NamespaceID")
  private String namespaceID = null;

  public RdfStats size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(value = "")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public RdfStats nrTriples(Integer nrTriples) {
    this.nrTriples = nrTriples;
    return this;
  }

   /**
   * Get nrTriples
   * @return nrTriples
  **/
  @ApiModelProperty(value = "")
  public Integer getNrTriples() {
    return nrTriples;
  }

  public void setNrTriples(Integer nrTriples) {
    this.nrTriples = nrTriples;
  }

  public RdfStats nrNodes(Integer nrNodes) {
    this.nrNodes = nrNodes;
    return this;
  }

   /**
   * Get nrNodes
   * @return nrNodes
  **/
  @ApiModelProperty(value = "")
  public Integer getNrNodes() {
    return nrNodes;
  }

  public void setNrNodes(Integer nrNodes) {
    this.nrNodes = nrNodes;
  }

  public RdfStats nrBlankNodes(Integer nrBlankNodes) {
    this.nrBlankNodes = nrBlankNodes;
    return this;
  }

   /**
   * Get nrBlankNodes
   * @return nrBlankNodes
  **/
  @ApiModelProperty(value = "")
  public Integer getNrBlankNodes() {
    return nrBlankNodes;
  }

  public void setNrBlankNodes(Integer nrBlankNodes) {
    this.nrBlankNodes = nrBlankNodes;
  }

  public RdfStats nrLiterals(Integer nrLiterals) {
    this.nrLiterals = nrLiterals;
    return this;
  }

   /**
   * Get nrLiterals
   * @return nrLiterals
  **/
  @ApiModelProperty(value = "")
  public Integer getNrLiterals() {
    return nrLiterals;
  }

  public void setNrLiterals(Integer nrLiterals) {
    this.nrLiterals = nrLiterals;
  }

  public RdfStats nrURINodes(Integer nrURINodes) {
    this.nrURINodes = nrURINodes;
    return this;
  }

   /**
   * Get nrURINodes
   * @return nrURINodes
  **/
  @ApiModelProperty(value = "")
  public Integer getNrURINodes() {
    return nrURINodes;
  }

  public void setNrURINodes(Integer nrURINodes) {
    this.nrURINodes = nrURINodes;
  }

  public RdfStats nrType(Integer nrType) {
    this.nrType = nrType;
    return this;
  }

   /**
   * Get nrType
   * @return nrType
  **/
  @ApiModelProperty(value = "")
  public Integer getNrType() {
    return nrType;
  }

  public void setNrType(Integer nrType) {
    this.nrType = nrType;
  }

  public RdfStats maxInDegree(Integer maxInDegree) {
    this.maxInDegree = maxInDegree;
    return this;
  }

   /**
   * Get maxInDegree
   * @return maxInDegree
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxInDegree() {
    return maxInDegree;
  }

  public void setMaxInDegree(Integer maxInDegree) {
    this.maxInDegree = maxInDegree;
  }

  public RdfStats maxOutDegree(Integer maxOutDegree) {
    this.maxOutDegree = maxOutDegree;
    return this;
  }

   /**
   * Get maxOutDegree
   * @return maxOutDegree
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxOutDegree() {
    return maxOutDegree;
  }

  public void setMaxOutDegree(Integer maxOutDegree) {
    this.maxOutDegree = maxOutDegree;
  }

  public RdfStats maxDegree(Integer maxDegree) {
    this.maxDegree = maxDegree;
    return this;
  }

   /**
   * Get maxDegree
   * @return maxDegree
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxDegree() {
    return maxDegree;
  }

  public void setMaxDegree(Integer maxDegree) {
    this.maxDegree = maxDegree;
  }

  public RdfStats maxInDegreeNode(String maxInDegreeNode) {
    this.maxInDegreeNode = maxInDegreeNode;
    return this;
  }

   /**
   * Get maxInDegreeNode
   * @return maxInDegreeNode
  **/
  @ApiModelProperty(value = "")
  public String getMaxInDegreeNode() {
    return maxInDegreeNode;
  }

  public void setMaxInDegreeNode(String maxInDegreeNode) {
    this.maxInDegreeNode = maxInDegreeNode;
  }

  public RdfStats maxOutDegreeNode(String maxOutDegreeNode) {
    this.maxOutDegreeNode = maxOutDegreeNode;
    return this;
  }

   /**
   * Get maxOutDegreeNode
   * @return maxOutDegreeNode
  **/
  @ApiModelProperty(value = "")
  public String getMaxOutDegreeNode() {
    return maxOutDegreeNode;
  }

  public void setMaxOutDegreeNode(String maxOutDegreeNode) {
    this.maxOutDegreeNode = maxOutDegreeNode;
  }

  public RdfStats maxDegreeNode(String maxDegreeNode) {
    this.maxDegreeNode = maxDegreeNode;
    return this;
  }

   /**
   * Get maxDegreeNode
   * @return maxDegreeNode
  **/
  @ApiModelProperty(value = "")
  public String getMaxDegreeNode() {
    return maxDegreeNode;
  }

  public void setMaxDegreeNode(String maxDegreeNode) {
    this.maxDegreeNode = maxDegreeNode;
  }

  public RdfStats namespaceID(String namespaceID) {
    this.namespaceID = namespaceID;
    return this;
  }

   /**
   * Get namespaceID
   * @return namespaceID
  **/
  @ApiModelProperty(value = "")
  public String getNamespaceID() {
    return namespaceID;
  }

  public void setNamespaceID(String namespaceID) {
    this.namespaceID = namespaceID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RdfStats rdfStats = (RdfStats) o;
    return Objects.equals(this.size, rdfStats.size) &&
        Objects.equals(this.nrTriples, rdfStats.nrTriples) &&
        Objects.equals(this.nrNodes, rdfStats.nrNodes) &&
        Objects.equals(this.nrBlankNodes, rdfStats.nrBlankNodes) &&
        Objects.equals(this.nrLiterals, rdfStats.nrLiterals) &&
        Objects.equals(this.nrURINodes, rdfStats.nrURINodes) &&
        Objects.equals(this.nrType, rdfStats.nrType) &&
        Objects.equals(this.maxInDegree, rdfStats.maxInDegree) &&
        Objects.equals(this.maxOutDegree, rdfStats.maxOutDegree) &&
        Objects.equals(this.maxDegree, rdfStats.maxDegree) &&
        Objects.equals(this.maxInDegreeNode, rdfStats.maxInDegreeNode) &&
        Objects.equals(this.maxOutDegreeNode, rdfStats.maxOutDegreeNode) &&
        Objects.equals(this.maxDegreeNode, rdfStats.maxDegreeNode) &&
        Objects.equals(this.namespaceID, rdfStats.namespaceID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(size, nrTriples, nrNodes, nrBlankNodes, nrLiterals, nrURINodes, nrType, maxInDegree, maxOutDegree, maxDegree, maxInDegreeNode, maxOutDegreeNode, maxDegreeNode, namespaceID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RdfStats {\n");
    
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    nrTriples: ").append(toIndentedString(nrTriples)).append("\n");
    sb.append("    nrNodes: ").append(toIndentedString(nrNodes)).append("\n");
    sb.append("    nrBlankNodes: ").append(toIndentedString(nrBlankNodes)).append("\n");
    sb.append("    nrLiterals: ").append(toIndentedString(nrLiterals)).append("\n");
    sb.append("    nrURINodes: ").append(toIndentedString(nrURINodes)).append("\n");
    sb.append("    nrType: ").append(toIndentedString(nrType)).append("\n");
    sb.append("    maxInDegree: ").append(toIndentedString(maxInDegree)).append("\n");
    sb.append("    maxOutDegree: ").append(toIndentedString(maxOutDegree)).append("\n");
    sb.append("    maxDegree: ").append(toIndentedString(maxDegree)).append("\n");
    sb.append("    maxInDegreeNode: ").append(toIndentedString(maxInDegreeNode)).append("\n");
    sb.append("    maxOutDegreeNode: ").append(toIndentedString(maxOutDegreeNode)).append("\n");
    sb.append("    maxDegreeNode: ").append(toIndentedString(maxDegreeNode)).append("\n");
    sb.append("    namespaceID: ").append(toIndentedString(namespaceID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

