swagger: '2.0'
info:
  description: >-
    This is DaCA's Uploader service.  You can find out more about     us at
    [https://github.com/catalin-vlas/DaCA](DaCA).
  version: 1.0.0
  title: DaCAUploader
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: aurelian.hreapca@info.uaic.ro
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:1995'
basePath: /
tags:
  - name: Upload
    description: DaCA Upload
    externalDocs:
      description: Find out more
      url: 'https://github.com/catalin-vlas/DaCA'
schemes:
  - http
paths:
  '/upload/{namespaceId}':
    put:
      tags:
        - Upload
      summary: Upload triples from file
      description: ''
      operationId: uploadFromFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: namespaceId
          in: path
          description: The namespace in which the upload will be done
          required: true
          type: string
        - name: file
          in: formData
          description: File containing triples
          required: true
          type: file
      responses:
        '200':
          description: Success
        '405':
          description: Invalid input
  '/upload/{namespaceId}/{url}':
    put:
      tags:
        - Upload
      summary: Upload triples from URL
      description: ''
      operationId: uploadFromUrl
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: namespaceId
          in: path
          description: The namespace in which the upload will be done
          required: true
          type: string
        - name: url
          in: path
          description: The URL from which triples are to be uploaded
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              type: string
        '405':
          description: Invalid input
externalDocs:
  description: Find out more about DaCA
  url: 'https://github.com/catalin-vlas/DaCA'
